// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD90Jc1p9rXCiuUEtWHkPX7EWzpmfa_F70',
    appId: '1:178992107250:web:2f4e129ca19c39fca70a6b',
    messagingSenderId: '178992107250',
    projectId: 'pioneerspalm-78855',
    authDomain: 'pioneerspalm-78855.firebaseapp.com',
    databaseURL: 'https://pioneerspalm-78855-default-rtdb.firebaseio.com',
    storageBucket: 'pioneerspalm-78855.firebasestorage.app',
    measurementId: 'G-YD53J98DH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADP46mnaD5JwM0TsFPYEzIsxMmTzgvuYs',
    appId: '1:178992107250:android:616ff7719bfa9083a70a6b',
    messagingSenderId: '178992107250',
    projectId: 'pioneerspalm-78855',
    databaseURL: 'https://pioneerspalm-78855-default-rtdb.firebaseio.com',
    storageBucket: 'pioneerspalm-78855.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5HOCI1mkOIZMgf6weBOUihkPrHeorlng',
    appId: '1:178992107250:ios:1c7aba757c102302a70a6b',
    messagingSenderId: '178992107250',
    projectId: 'pioneerspalm-78855',
    databaseURL: 'https://pioneerspalm-78855-default-rtdb.firebaseio.com',
    storageBucket: 'pioneerspalm-78855.firebasestorage.app',
    iosBundleId: 'com.example.smartFert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5HOCI1mkOIZMgf6weBOUihkPrHeorlng',
    appId: '1:178992107250:ios:1c7aba757c102302a70a6b',
    messagingSenderId: '178992107250',
    projectId: 'pioneerspalm-78855',
    databaseURL: 'https://pioneerspalm-78855-default-rtdb.firebaseio.com',
    storageBucket: 'pioneerspalm-78855.firebasestorage.app',
    iosBundleId: 'com.example.smartFert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD90Jc1p9rXCiuUEtWHkPX7EWzpmfa_F70',
    appId: '1:178992107250:web:0b2c6bd31a634568a70a6b',
    messagingSenderId: '178992107250',
    projectId: 'pioneerspalm-78855',
    authDomain: 'pioneerspalm-78855.firebaseapp.com',
    databaseURL: 'https://pioneerspalm-78855-default-rtdb.firebaseio.com',
    storageBucket: 'pioneerspalm-78855.firebasestorage.app',
    measurementId: 'G-NLM0QGX4DX',
  );
}
